/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BarbieFunToken__factory } from "./BarbieFunToken__factory";
export { BarbieFunTokenFactory__factory } from "./BarbieFunTokenFactory__factory";
